### ISSUE TITLE
The seo_title does not seem to be working

### ISSUE THREAD

**Issue by robertgriffincastlegateit** [castlegateit/cgit-wp-acf-seo#1]
I can't get the seo_title to appear automatically, or by manually echoing cgit_seo_title(): or seo_title(); within my theme's header.

Am falling back to using the following instead:

<title><?php wp_title('|', TRUE, 'right'); ?></title>

**Comment by johnkhughes** [comment]
As far as I can tell, the plugin is working as intended. You shouldn't have to change your templates (see README.md!); you just use `wp_title(...)` as usual.
