### ISSUE TITLE
Request: SEO Preview

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-acf-seo#2]
Plugins such as the All in One SEO pack display a nice preview above the SEO fields, showing how the entry may look in Google search results.

We could add something similar to help clients improve their entries. This should only be shown if the fields have values, so not to make users believe they must enter something beyond the defaults.

The fields should have character limits, or the preview should show when the recommended limits are exceeded. Some additional help text or field descriptions may also be worth adding.

**Comment by johnkhughes** [comment]
If we need all Yoast's features, we can use Yoast. I'm going to close this because I think it is now out of scope for this plugin.
