### ISSUE TITLE
Doesn't this acutally require ACF Pro?

### ISSUE THREAD

**Issue by richplane** [castlegateit/cgit-wp-acf-seo#3]
The repo uses the function acf_add_local_field_group() which is only defined in ACF Pro AFAIK.

**Comment by johnkhughes** [comment]
I think you're right. But is that a problem?

**Comment by richplane** [comment]
Well the readme says "Requires Advanced Custom Fields" so if we decide it's OK to require Pro then we need to update that at least!

**Comment by johnkhughes** [comment]
Fair point. I'll update it.
